web_applications/l_log/l_log/urls.py
# user requests ## p413
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path(
        'admin/'
        , admin.site.urls
    ),
    
    # include users ## p439
    path(
        'users/'
        , include('users.urls')
    ),

    # include URLs from l_logs ## p413
    path(
        ''
        , include('l_logs.urls')
    ),
]

web_applications/l_log/l_logs/urls.py
"""Define URL patterns for l_logs."""

# user requests ## p413
from django.urls import path

# map URL to views ## p413
from . import views

# identify app ## p413
app_name = 'l_logs'

# list of pages accesible for this app ## p413
urlpatterns = [
    # home page ## p413
    path(
        ''
        , views.index
        , name='index'
    ),

    # show all topics. # p419
    path(
        'topics/'
        , views.topics
        , name='topics'
    ),

    # detail page for a single topic. ## p422
    path(
        'topics/<int:topic_id>/'
        , views.topic
        , name='topic'
    ),

    # page for adding a new topic. ## p429
    path(
        'new_topic/'
        , views.new_topic
        , name='new_topic'
    ),

    # page for adding a new entry. ## 433
    path(
        'new_entry/<int:topic_id>/'
        , views.new_entry
        , name='new_entry'
    ),

    # page for editing an entry. ## 436
    path(
        'edit_entry/<int:entry_id>/'
        , views.edit_entry
        , name='edit_entry'
    ),
]

web_applications/l_log/users/urls.py
"""Defines URL patterns for users."""

# user requests ## p440
from django.urls import path
from django.contrib.auth import login

from . import views


app_name = 'users'

urlpatterns = [
    # login page ## p440
    path(
        'login/'
        , login
        #, {'template_name': 'users/login.html'}
        , name='login'
    ),
    path(
        'logout/'
        , views.logout_view
        , name='logout'
    ),
]

web_applications/l_log/l_logs/models.py
# Create your models here.
# modify models, then migrate the db ## p409

from django.db import models


## p403
class Topic(models.Model):
	"""A topic the user is learning about."""
	text = models.CharField(
        max_length=200
        )
	date_added = models.DateTimeField(
        auto_now_add=True
        )
	
	def __str__(self):
		"""Return a string representation of the model."""
		return self.text


## p408
class Entry(models.Model):
	"""Something specific learned about topic."""
	topic = models.ForeignKey(
        Topic
        , on_delete=models.CASCADE
        )
	text = models.TextField()
	date_added = models.DateTimeField(
        auto_now_add=True
        )
	
	class Meta:
		verbose_name_plural = 'entries'
	
	def __str__(self):
		"""Return a string representation of the model."""
		if len(self.text) > 50:
			text = self.text[0:50]
		else:
			text = self.text
			
		return text

web_applications/l_log/users/models.py
from django.db import models

# Create your models here.

web_applications/l_log/l_logs/forms.py
### Allow users to enter data

## p428
from django import forms


## p428 p432
from .models import Topic, Entry


# ModelForm for Topic ## p428
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


# ModelForm for Entry ## p432
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

web_applications/l_log/l_logs/views.py
# Create your views here.

from django.shortcuts import render
# new topic ## p429
from django.http import HttpResponseRedirect
# new topic ## p429
from django.urls import reverse


# topic ## p419 p436
from .models import Topic, Entry
# new topic ## p429 p433
from .forms import TopicForm, EntryForm


# render home page ## p415
def index(request):
    """Home page for l_log."""
    return render(
        request
        , 'l_logs/index.html'
        )


# render topics page. ## p419
def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(
        request
        , 'l_logs/topics.html'
        , context
        )


# render single topic page. ## p422
def topic(
    request
    , topic_id
    ):
    """Show a single topic with all entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic
        , 'entries': entries
        }
    return render(
        request
        , 'l_logs/topic.html'
        , context
        )


# new topic ## p429
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(
            data=request.POST
            )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('l_logs:topics')
                )

    context = {'form': form}
    return render(
        request
        , 'l_logs/new_topic.html'
        , context
        )


# new topic ## p429
def new_entry(
    request
    , topic_id
    ):
    """Add a new entry for specific topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(
            data=request.POST
            )
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(
                reverse(
                    'l_logs:topic'
                    , args=[topic_id]
                    )
                )

    context = {'topic': topic, 'form': form}
    return render(
        request
        , 'l_logs/new_entry.html'
        , context
        )


# edit entry ## p436
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    
    if request.method != 'POST':
        # Initial request; pre-fill form with current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(
            instance=entry
            , data=request.POST
            )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse(
                    'l_logs:topic'
                    , args=[topic.id]
                    )
                )

    context = {
        'entry': entry
        , 'topic': topic
        , 'form': form
        }
    return render(
        request
        , 'l_logs/edit_entry.html'
        , context
        )

web_applications/l_log/users/views.py
# logout ## p443
from django.contrib.auth import authenticate, login, logout

from django.http import HttpResponseRedirect
from django.urls import reverse


def my_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.

        if request.user.is_authenticated:
            # Do something for authenticated users.
            #...
        else:
            # Do something for anonymous users.
            #...
    else:
        # Return an 'invalid login' error message.
        #...

# logout view ## p443
def logout_view(request):
    """Log the user out."""

    # call the logout ## p443
    logout(request)
    # redirect to success page ## p443
    return HttpResponseRedirect(
        reverse('l_logs:index')
    )

web_applications/l_log/l_logs/templates/l_logs/base.html
<p>
  <a href="{% url 'l_logs:index' %}">L Log</a> |

  <a href="{% url 'l_logs:topics' %}">Topics</a> |

  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    (<a href="{% url 'users:logout' %}">log out</a>)
  {% else %}
    <a href="{% url 'users:login' %}">log in</a>
  {% endif %}

</p>

{% block content %}{% endblock content %}

<hr />

<p>(c) Aleksandras Urbonas. 2018</p>.

web_applications/l_log/l_logs/templates/l_logs/edit_entry.html
{% extends "l_logs/base.html" %}

{% block content %}

  <p>
    <a
      href="{% url 'l_logs:topic' topic.id %}"
    >
      {{ topic }}
    </a>
  </p>

  <p>
    Edit entry:
  </p>

  <form
    action="{% url 'l_logs:edit_entry' entry.id %}"
    method='post'
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button
      name="submit"
    >
      save changes
    </button>
  </form>

{% endblock content %}

web_applications/l_log/l_logs/templates/l_logs/index.html
{% extends "l_logs/base.html" %}

{% block content %}

<p>L Log helps you track your learning, for any topic of interest.</p>

{% endblock content %}

web_applications/l_log/l_logs/templates/l_logs/new_entry.html
{% extends "l_logs/base.html" %}

{% block content %}

  <p>
    <a
      href="{% url 'l_logs:topic' topic.id %}"
    >
      {{ topic }}
    </a>
  </p>

  <p>
    Add a new entry:
  </p>

  <form
    action="{% url 'l_logs:new_entry' topic.id %}"
    method='post'
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button
      name="submit"
    >
      add entry
    </button>
  </form>

{% endblock content %}

web_applications/l_log/l_logs/templates/l_logs/new_topic.html
{% extends "l_logs/base.html" %}

{% block content %}

  <p>
    Add a new topic:
  </p>

  <form
    action="{% url 'l_logs:new_topic' %}"
    method='post'
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button
      name="submit"
    >
      add topic
    </button>
  </form>

{% endblock content %}

web_applications/l_log/l_logs/templates/l_logs/topic.html
{% extends "l_logs/base.html" %}

{% block content %}

    <p>
      Topic: {{ topic }}
    </p>

    <p>
      Entries:
    </p>
    <p>
      <a
        href="{% url 'l_logs:new_entry' topic.id %}"
      >
        add new entry
      </a>

    <ul>
    {% for entry in entries %}
      <li>
        <p>
          {{ entry.date_added|date:'M d, Y H:i' }}
        </p>
        <p>
          {{ entry.text|linebreaks }}
        </p>
        <p>
          <a
            href="{% url 'l_logs:edit_entry' entry.id %}"
          >
            edit entry
          </a>
        </p>
      </li>
      <hr />
    {% empty %}
      <li>
        There are no entries for this topic yet.
      </li>
    {% endfor %}
    </ul>

    <p>
      Available records end here.
    </p>

{% endblock content %}

web_applications/l_log/l_logs/templates/l_logs/topics.html
{% extends "l_logs/base.html" %}

{% block content %}

  <p>
    Topics
  </p>

  <ul>
  {% for topic in topics %}
    <li>
      <a
        href="{% url 'l_logs:topic' topic.id %}"
      >
        {{ topic }}
      </a>
    </li>
  {% empty %}
    <li>No topics have been added yet.</li>
  {% endfor %}
  </ul>

  <a
    href="{% url 'l_logs:new_topic' %}"
  >
    Add a new topic:
  </a>

{% endblock content %}

web_applications/l_log/users/templates/users/login.html
{% extends "l_logs/base.html" %}

{% block content %}

  {% if form.errors %}
    <p>
        Your username and password do not match. Please try again.
    </p>
  {% endif %}

  <form
    method="post"
    action="{% url 'users:login' %}"
  >
    {% csrf_token %}
    {{ form.as_p }}
    
    <button
      name="submit"
    >
      log in
    </button>

    <input
      type="hidden"
      name="next"
      value="{% url 'l_logs:index' %}"
    >

  </form>

{% endblock content %}